defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: todos_development

test:
  <<: *defaults
  database: todos_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: todos
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>

# to configure with a uri use:
# uri: <%= ENV['MONGODB_URI'] %>